name: Deploy to Dev EC2

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        run: docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development

    steps:
      - name: Deploy to Dev EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            export IMAGE_NAME=ghcr.io/${{ github.repository }}:dev
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker stop webapp || true
            docker rm webapp || true
            docker pull $IMAGE_NAME
            docker run -d --name webapp -p 80:80 $IMAGE_NAME