name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

env:
  IMAGE_NAME: ghcr.io/${{ secrets.GHCR_USERNAME }}/separate-env-project

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        TAG=${{ github.ref_name == 'main' && 'prod' || 'dev' }}
        docker build -t $IMAGE_NAME:$TAG .

    - name: Push Docker Image
      run: |
        TAG=${{ github.ref_name == 'main' && 'prod' || 'dev' }}
        docker push $IMAGE_NAME:$TAG

  deploy-dev:
    name: Deploy to EC2 Dev
    if: github.ref_name == 'dev'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: SSH and Deploy to Dev EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_DEV_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_PAT }}
          docker stop webapp || true
          docker rm webapp || true
          docker pull $IMAGE_NAME:dev
          docker run -d --name webapp -p 80:80 $IMAGE_NAME:dev

  deploy-prod:
    name: Deploy to EC2 Prod
    if: github.ref_name == 'main'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://${{ secrets.EC2_PROD_HOST }}
    concurrency: production
    steps:
    - name: Wait for Manual Approval
      uses: hmarr/auto-approve-action@v3
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: SSH and Deploy to Prod EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_PROD_HOST }}
        username: ${{ secrets.EC2_SSH_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_PAT }}
          docker stop webapp || true
          docker rm webapp || true
          docker pull $IMAGE_NAME:prod
          docker run -d --name webapp -p 80:80 $IMAGE_NAME:prod
