name: Deploy to Prod EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:prod .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
      - name: Deploy to Prod EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          envs: IMAGE_NAME
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            docker stop webapp || true
            docker rm webapp || true
            docker pull $IMAGE_NAME
            docker run -d --name webapp -p 80:80 $IMAGE_NAME
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}:prod